### ISSUE TITLE
Polar Bears Doesn't Attack Back

### ISSUE THREAD

**Issue by pofdzm** [etil2jz/Mirai#21]
[as you can see here: https://youtu.be/wbI4oLLoTjg](https://youtu.be/wbI4oLLoTjg)

**Comment by pofdzm** [comment]
Though, weird enough, it does attack when I summon one with the /summon command.

**Comment by etil2jz** [comment]
Can I please have your plugin list? Generated a world with seed `638773` and polar bears next to me attacked me when I approached them

**Comment by pofdzm** [comment]
> Can I please have your plugin list? Generated a world with seed `638773` and polar bears next to me attacked me when I approached them

I have no plugins, I just downloaded the jar and ran it.

**Comment by etil2jz** [comment]
Can you try generate a new world, approach a polar bear while being in survival mode on **latest** build

**Comment by pofdzm** [comment]
I believe it was already the latest build, I downloaded that file named "Mirai-1.18.2-R0.1-SNAPSHOT.jar", I downloaded it yesterday, I will also try the thing you said when I'm at home.

**Comment by ghost** [comment]
You don't even have to try, because the bears work fine. I just checked on the latest version of 2 kernels. Versions with Pufferfish & Purpur. Generated a world, found a biome with bears and hit them in survival mode. That said, I didn't have a peaceful difficulty. I think it affects it, maybe it doesn't.

**Comment by etil2jz** [comment]
Closing this issue as I and other users cannot reproduce it.
